const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const products = [
  {
    style: "Forta Run K Sneaker",
    brand: "Nike",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 114.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers1-E1lMkzbVidlnGUoGQbBsjN5XdaP06K.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "GV Special+ Sneaker",
    brand: "Puma",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 104.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers2-sTJVvu7kn1ii1vWNmeq5GcW2JDlyWO.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Suede XXI Sneaker",
    brand: "Puma",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 124.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers3-WzwIKTAVOV87Tle4E5oE3znmUSLdLz.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Low-rise Crew Sneaker",
    brand: "DNA Athletics",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 164.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers4-pY5eNiA5GZayfNBihVMFaNt0kHjoIn.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Cruise Rider Sneaker",
    brand: "DNA Athletics",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 194.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers5-ekJc0rMAkygBkTa5Pm4KD8DaX4Kwqn.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Air Max 3250",
    brand: "Nike",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 159.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers6-5S1veJOTNkgUVfSMrSQfeVbbJciGBQ.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Suede Yael Sneaker",
    brand: "DNA Athletics",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 114.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers7-6tRQhl9HvFPOK5Ld3ULOgUdphZw5I7.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Solaris Sneaker",
    brand: "Calvin Klein",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 214.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers8-X4ryYdmjoKcowYKVrhoPSrGTSqdD0T.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Revolution 8 Sneaker",
    brand: "Nike",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 134.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/sneakers/sneakers9-2u0YtE0oGsSkCKWS7L933iIiDD5Bh9.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Sparkling Elegance Pump",
    brand: "Jimmy Choo",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 449.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe1-5BITLqg9KRi1aQDS0nE79oDMiVmKLH.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Cobalt Classic Pump",
    brand: "Aldo",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 74.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe2-2uKtAKYczeNEe4tuEYzGvfn6HM2mGY.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Bring It Black Patent Pump",
    brand: "Michael Kors",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 249.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe3-DyUaxwgsM7gsG7SKrsIUAp5kix96v6.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Slate Suede Stiletto",
    brand: "Pokemaoke",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 154.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe4-LYClwRTVIH4FTr9eIzimozPRZauLCx.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Nude Sophistication Pump",
    brand: "Chanel",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 649.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe5-0kLd8EnvMRKnDnb5ZfV2hlwkvdb7UM.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Teal Dreams Oxford",
    brand: "Pokemaoke",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 124.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe6-po3zFPxgOJCe0ktlFbsDSqTPKJN0wQ.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Desert Chic Bootie",
    brand: "Michael Kors",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 314.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe7-eB5LowMA2x0cwtE0ntEOIFb4lN9pvV.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Magenta Glamour Stiletto",
    brand: "Franco Sarto",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 114.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe8-lRJkqvs9eLJHQk0iI0Zmcc2kAkC7E5.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Soft Blush Ballet Flat",
    brand: "Chie Mihar",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 174.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/dressShoes/dressShoe9-B26U20a1h9FrrwrxpcTv1kF2bmzsx5.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Cap Toe Lace Boot",
    brand: "Florsheim Shoes",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 124.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot1-jVmj8U7WQzoSt5FNvZciY853MdPRVk.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Classic Boot - Rouge",
    brand: "Michael Kors",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 169.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot2-k80yGnoVinS4ut4Iv8UAbbyFc4reWN.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Chelsea Cool Booties",
    brand: "Florsheim Shoes",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 149.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot3-59Eq7BCNYO6VN5Twh87od3Sn8Pl6An.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Montana Hiking Boot",
    brand: "Timberland",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 89.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot4-Rr7hRofNFAbPy3G2WXw1xIQXLjRZ5r.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Vintage Knee-High Boot",
    brand: "Moncler",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 144.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot5-KwvgyjABuJp8x4P9cHaTW36YPOvCva.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Roan Chelsea Boot",
    brand: "Blundstone",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 169.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot6-pYZI34Ji5J2BVMpKqpYimRi1CcpHLX.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Embossed Cowboy Boots",
    brand: "Corral Boot Co.",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 249.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot7-sio1-f41HROeqWdR937lX8KriQkaT2NMKk7.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Camo Waterproof Hiking Boot",
    brand: "Columbia",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 134.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot8-sio1-bLIV0iJmQTwhteMbMpVqttDD7focl9.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Block Heel Chelsea Boot",
    brand: "Sam Edelman",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 249.99,
    image_url: "https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/boots/boot9-sn2KPXWZxF0qdgpwsJyHF19jTm9saH.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
];

async function main() {
  for (const product of products) {
    await prisma.product.create({
      data: product,
    });
  }
}

main()
  .catch(e => {
    console.error("Error inserting data:", e);
  })
  .finally(async () => {
    // Disconnect the Prisma Client after the script is done
    await prisma.$disconnect();
  });
