const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const products = [
  {
    style: "Forta Run K Sneaker",
    brand: "Nike",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 114.99,
    image_url: "/assets/sneakers/sneakers1.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "GV Special+ Sneaker",
    brand: "Puma",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 104.99,
    image_url: "/assets/sneakers/sneakers2.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Suede XXI Sneaker",
    brand: "Puma",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 124.99,
    image_url: "/assets/sneakers/sneakers3.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Low-rise Crew Sneaker",
    brand: "DNA Athletics",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 164.99,
    image_url: "/assets/sneakers/sneakers4.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Cruise Rider Sneaker",
    brand: "DNA Athletics",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 194.99,
    image_url: "/assets/sneakers/sneakers5.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Air Max 3250",
    brand: "Nike",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 159.99,
    image_url: "/assets/sneakers/sneakers6.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Suede Yael Sneaker",
    brand: "DNA Athletics",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 114.99,
    image_url: "/assets/sneakers/sneakers7.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Solaris Sneaker",
    brand: "Calvin Klein",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 214.99,
    image_url: "/assets/sneakers/sneakers8.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Revolution 8 Sneaker",
    brand: "Nike",
    category: "sneakers",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 134.99,
    image_url: "/assets/sneakers/sneakers9.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Sparkling Elegance Pump",
    brand: "Jimmy Choo",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 449.99,
    image_url: "/assets/dressShoes/dressShoe1.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Cobalt Classic Pump",
    brand: "Aldo",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 74.99,
    image_url: "/assets/dressShoes/dressShoe2.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Bring It Black Patent Pump",
    brand: "Michael Kors",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 249.99,
    image_url: "/assets/dressShoes/dressShoe3.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Slate Suede Stiletto",
    brand: "Pokemaoke",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 154.99,
    image_url: "/assets/dressShoes/dressShoe4.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Nude Sophistication Pump",
    brand: "Chanel",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 649.99,
    image_url: "/assets/dressShoes/dressShoe5.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Teal Dreams Oxford",
    brand: "Pokemaoke",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 124.99,
    image_url: "/assets/dressShoes/dressShoe6.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Desert Chic Bootie",
    brand: "Michael Kors",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 314.99,
    image_url: "/assets/dressShoes/dressShoe7.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Magenta Glamour Stiletto",
    brand: "Franco Sarto",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 114.99,
    image_url: "/assets/dressShoes/dressShoe8.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Soft Blush Ballet Flat",
    brand: "Chie Mihar",
    category: "dress shoes",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 174.99,
    image_url: "/assets/dressShoes/dressShoe9.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Montana Hiking Boot",
    brand: "Columbia",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 124.99,
    image_url: "/assets/boots/boot1.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Classic Boot - Rouge",
    brand: "Timberland",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 169.99,
    image_url: "/assets/boots/boot2.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Cap Toe Lace Boot",
    brand: "Florsheim Shoes",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 149.99,
    image_url: "/assets/boots/boot3.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Waterproof Hiking Boot",
    brand: "Outdoors",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 89.99,
    image_url: "/assets/boots/boot4.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Ridge Hiking Boot",
    brand: "Moncler",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 144.99,
    image_url: "/assets/boots/boot5.jpg",
    new_arrival: true,
    avg_star_rating: 0.0,
  },
  {
    style: "Classic Rustic Boot",
    brand: "Blundstone",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 214.99,
    image_url: "/assets/boots/boot6.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Classic Boot - Tobacco",
    brand: "Timberland",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 169.99,
    image_url: "/assets/boots/boot7.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Maddsen Waterproof Boot",
    brand: "Timberland",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 134.99,
    image_url: "/assets/boots/boot8.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
  {
    style: "Rosé Hiking Boot",
    brand: "Michael Kors",
    category: "boots",
    sizes: [6, 7, 8, 9, 10, 11],
    price: 249.99,
    image_url: "/assets/boots/boot9.jpg",
    new_arrival: false,
    avg_star_rating: 0.0,
  },
];

async function main() {
  for (const product of products) {
    await prisma.product.create({
      data: product,
    });
  }
}

main()
  .catch(e => {
    console.error("Error inserting data:", e);
  })
  .finally(async () => {
    // Disconnect the Prisma Client after the script is done
    await prisma.$disconnect();
  });
