import "@/styles/normalize.css";
import "@/styles/globals.css";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { useState, useEffect } from "react";

/* eslint-disable react/prop-types */
export default function App({ Component, pageProps }) {
  const [itemOrder, setItemOrder] = useState(null);
  const [orderData, setOrderData] = useState(null);
  const [orderTotal, setOrderTotal] = useState(0);
  const [product, setProduct] = useState();
  const [productInfo, setProductInfo] = useState([]);
  const [category, setCategory] = useState();
  // const [quantity, setQuantity] = useState(0);
  // const [selectedSize, setSelectedSize] = useState("6");

  return (
    <>
      <Head>
        <title>shop shoos</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <Header itemOrder={itemOrder} orderData={orderData} orderTotal={orderTotal} category={category} setCategory={setCategory} />
      <main>
        <Component
          {...pageProps}
          orderData={orderData}
          setOrderData={setOrderData}
          setItemOrder={setItemOrder}
          itemOrder={itemOrder}
          productInfo={productInfo}
          setProductInfo={setProductInfo}
          setOrderTotal={setOrderTotal}
          product={product}
          setProduct={setProduct}
          // quantity={quantity}
          // setQuantity={setQuantity}
          // selectedSize={selectedSize}
          // setSelectedSize={setSelectedSize}
        />
      </main>
      <Footer />
    </>
  );
}
