/* eslint-disable react/react-in-jsx-scope */
// import { useState } from "react";
import Head from "next/head";

/* eslint-disable react/prop-types */
export default function Checkout(props) {
  const { orderData, orderTotal } = props;

  // addOrderDetails().then(data => {
  //   addItemDetails(data.id);
  // });

  const addOrderDetails = async () => {
    const body = { orderData };

    const response = await fetch("/api/post/addOrder", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    const data = await response.json();
    return data;
  };

  const addItemDetails = async bag_id => {
    const body = { itemOrder, bag_id };
    const response = await fetch("/api/post/addItem", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    const data = await response.json();
  };

  return (
    <>
      <Head>
        <title>Shoos Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='outerWrapper'>
        <div
          className='banner checkoutBanner'
          style={{
            backgroundImage: 'url("https://krwzqpaj7utmeydl.public.blob.vercel-storage.com/banners/aboutUsBanner-bkRtuyvIna278vVgeJOajZgntDH8gj.jpg")',
          }}
        >
          <h2 className='category'>Checkout</h2>
        </div>
        <div className='wrapper'>
          <section className='checkout'>
            <h5>Order Details</h5>
            {orderData ? (
              orderData.map((shoe, index) => {
                return (
                  <div className='orderDetails' key={index}>
                    <img src={shoe.src} alt='' />
                    <div>
                      <p className='brand'>{shoe.brand}</p>
                      <p className='style'>{shoe.style}</p>
                      <p className='size'>Size: {shoe.size}</p>
                    </div>
                    <div>
                      <p className='qty'>Qty</p>
                      <p className='price'>Price</p>
                    </div>
                    <div>
                      <p className='qty qtyNum'>{shoe.quantity}</p>
                      <p className='price'>{shoe.price}</p>
                    </div>
                  </div>
                );
              })
            ) : (
              <p>Your Shopping Bag is Empty</p>
            )}
            <div className='total'>
              <p>Total:</p>
              <p>${orderTotal === 0 ? "0.00" : orderTotal}</p>
            </div>
          </section>
        </div>
      </div>
    </>
  );
}
