/* eslint-disable react/react-in-jsx-scope */
// import { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Image from "next/image";
import ReviewForm from "../components/ReviewForm";

export default function Checkout(props) {
    const { orderData, orderTotal } = props;

    return (
        <>
            <Head>
                <title>Shoos Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="outerWrapper">
                <Header></Header>
                <div className="banner checkoutBanner">
                    <h2 className="category">Checkout</h2>
                </div>
                <div className="wrapper">
                    <section className="checkout">
                        <h5>Order Details</h5>
                        {orderData ? (
                            orderData.map((shoe, index) => {
                                return (
                                    <div className="orderDetails" key={index}>
                                        <img src={shoe.src} alt="" />
                                        <div>
                                            <p className="brand">
                                                {shoe.brand}
                                            </p>
                                            <p className="style">
                                                {shoe.style}
                                            </p>
                                            <p className="size">
                                                Size: {shoe.size}
                                            </p>
                                        </div>
                                        <div>
                                            <p className="qty">Qty</p>
                                            <p className="price">Price</p>
                                        </div>
                                        <div>
                                            <p className="qty qtyNum">
                                                {shoe.quantity}
                                            </p>
                                            <p className="price">
                                                {shoe.price}
                                            </p>
                                        </div>
                                    </div>
                                );
                            })
                        ) : (
                            <p>Your Shopping Bag is Empty</p>
                        )}
                        <div className="total">
                            <p>Total:</p>
                            <p>${orderTotal === 0 ? "0.00" : orderTotal}</p>
                        </div>
                    </section>
                    <ReviewForm></ReviewForm>
                </div>
                <Footer></Footer>
            </div>
        </>
    );
}
