import { useState } from "react";
import Head from "next/head";
import shoeInfo from "@/shoeInfo";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Gallery from "@/components/Gallery";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [category, setCategory] = useState("New Arrivals");

    return (
        <>
            <Head>
                <title>Shoos Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Header setCategory={setCategory}></Header>
                <Gallery shoeInfo={shoeInfo} category={category}></Gallery>
            </main>
        </>
    );
}
