/* eslint-disable react/react-in-jsx-scope */
import { useState } from "react";
import Head from "next/head";
import shoeInfo from "@/shoeInfo";
// import styles from "@/styles/Home.module.css";
import LandingPage from "@/components/LandingPage";
// import prisma from "../lib/prisma";

export default function Home() {
    return (
        <>
            <Head>
                <title>Shoos Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="outerWrapper">
                <LandingPage shoeInfo={shoeInfo}></LandingPage>
            </div>
        </>
    );
}
